services:
  - type: web
    name: grow-teens-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: node --experimental-strip-types src/server.ts
